var _ = require('lodash');

var people = [{
  "id": 1,
  "first_name": "Annie",
  "last_name": "Sullivan",
  "email": "asullivan0@instagram.com",
  "gender": "Female",
  "ip_address": "24.80.147.61"
}, {
  "id": 2,
  "first_name": "Linda",
  "last_name": "Martin",
  "email": "lmartin1@blinklist.com",
  "gender": "Female",
  "ip_address": "50.209.146.245"
}, {
  "id": 3,
  "first_name": "James",
  "last_name": "Cruz",
  "email": "jcruz2@hostgator.com",
  "gender": "Male",
  "ip_address": "56.111.194.166"
}, {
  "id": 4,
  "first_name": "Gloria",
  "last_name": "Sullivan",
  "email": "gsullivan3@shinystat.com",
  "gender": "Female",
  "ip_address": "150.179.153.221"
}, {
  "id": 5,
  "first_name": "Thomas",
  "last_name": "Reid",
  "email": "treid4@illinois.edu",
  "gender": "Male",
  "ip_address": "37.223.153.127"
}, {
  "id": 6,
  "first_name": "Daniel",
  "last_name": "Johnson",
  "email": "djohnson5@ehow.com",
  "gender": "Male",
  "ip_address": "180.49.139.179"
}, {
  "id": 7,
  "first_name": "Janice",
  "last_name": "Walker",
  "email": "jwalker6@theguardian.com",
  "gender": "Female",
  "ip_address": "139.14.35.6"
}, {
  "id": 8,
  "first_name": "Jacqueline",
  "last_name": "Gray",
  "email": "jgray7@hostgator.com",
  "gender": "Female",
  "ip_address": "84.251.210.182"
}, {
  "id": 9,
  "first_name": "Victor",
  "last_name": "Smith",
  "email": "vsmith8@webmd.com",
  "gender": "Male",
  "ip_address": "195.175.8.120"
}, {
  "id": 10,
  "first_name": "Brian",
  "last_name": "Rodriguez",
  "email": "brodriguez9@de.vu",
  "gender": "Male",
  "ip_address": "123.37.228.188"
}, {
  "id": 11,
  "first_name": "Joshua",
  "last_name": "Lynch",
  "email": "jlyncha@bloglines.com",
  "gender": "Male",
  "ip_address": "233.90.15.152"
}, {
  "id": 12,
  "first_name": "Katherine",
  "last_name": "Lewis",
  "email": "klewisb@shinystat.com",
  "gender": "Female",
  "ip_address": "100.75.140.136"
}, {
  "id": 13,
  "first_name": "Mary",
  "last_name": "Spencer",
  "email": "mspencerc@auda.org.au",
  "gender": "Female",
  "ip_address": "176.212.212.175"
}, {
  "id": 14,
  "first_name": "Amanda",
  "last_name": "Arnold",
  "email": "aarnoldd@ovh.net",
  "gender": "Female",
  "ip_address": "29.101.237.8"
}, {
  "id": 15,
  "first_name": "Charles",
  "last_name": "Fuller",
  "email": "cfullere@webmd.com",
  "gender": "Male",
  "ip_address": "229.25.41.2"
}, {
  "id": 16,
  "first_name": "Tammy",
  "last_name": "Russell",
  "email": "trussellf@woothemes.com",
  "gender": "Female",
  "ip_address": "195.73.78.31"
}, {
  "id": 17,
  "first_name": "Russell",
  "last_name": "Gibson",
  "email": "rgibsong@prweb.com",
  "gender": "Male",
  "ip_address": "167.131.133.80"
}, {
  "id": 18,
  "first_name": "Susan",
  "last_name": "Murray",
  "email": "smurrayh@g.co",
  "gender": "Female",
  "ip_address": "5.81.31.167"
}, {
  "id": 19,
  "first_name": "Sara",
  "last_name": "Mills",
  "email": "smillsi@howstuffworks.com",
  "gender": "Female",
  "ip_address": "60.55.197.232"
}, {
  "id": 20,
  "first_name": "Jose",
  "last_name": "Cunningham",
  "email": "jcunninghamj@weibo.com",
  "gender": "Male",
  "ip_address": "222.71.185.155"
}]

var femaleCount = _.filter(people, {gender: "Female"}).length;
alert(femaleCount + " females!")